### ISSUE TITLE
Documentation missing essential information

### ISSUE THREAD

**Issue by bergwerf** [stormcolor/webclgl#12]
I want to write a Dart wrapper for `webclgl` and try to accelerate a particle simulation. It seems sufficient to wrap the `gpufor` function (Dart is transpiled to JS, and in order to use JS libraries in Dart you need to write a kind of wrapper library). Unfortunately, I could not find extensive information on what arguments can be passed to `gpufor`. It seems from https://rawgit.com/stormcolor/webclgl/master/APIdoc/APIdoc/WebCLGLFor.class.js.html that the arguments are kind of flexible. In Dart I have to provide multiple typed variants (this is actually very useful for the developer because the IDE can then provide better suggestions and type checking). Can you provide more information?

**Comment by fibabast** [comment]
Thank you for your mentions,but I have drop the webcl project for a long time. Since the factories of the gpu seem not willing to open more information,  I think it's more attainable to design some  plug-in to realize the funcitions you need.

**Comment by fibabast** [comment]
Thank you for your mentions,but I have drop the webcl project for a long time. Since the factories of the gpu seem not willing to open more information,  I think it's more attainable to design some  plug-in to realize the funcitions you need.

**Comment by hermanbergwerf** [comment]
Can you explain the extension a little more? I want to use it in a web-application. There is a WebCL spec but no browser has implemented it so far (I read Mozilla favours compute shaders that will arrive later in WebGL). GPU computations can also be performed via textures and shaders in WebGL, isn't webclgl a wrapper for this? I can also construct this directly in WebGL of course.

**Comment by 3DRoberto** [comment]
Currently the unique information available is contained in the readme, the demos and the Prefabs Graph, Grid and Camera of the SCEJS library.
https://github.com/stormcolor/SCEJS/blob/master/SCEJS/Prefabs/Graph
https://github.com/stormcolor/SCEJS/tree/master/SCEJS/Prefabs/Grid
https://github.com/stormcolor/SCEJS/tree/master/SCEJS/Prefabs/SimpleCamera

I intend to better document the library, especially for use in graphics mode.
These days I'm a bit full but I will try to improve the status of documentation as soon as I have some more time.

Regards ;)

**Comment by fibabast** [comment]
It's an alternative method by which you use the shader language to do computering. However, there are some limits in the webgl such as the memory restrict and the speed restrict that you can't use the gpu completely and effciently. The essential question is that what do you want to do with the general purpose compution, and is it useful and worth to do it in webbrower. If you really need to realize the physical effects, you can do some approximate calculation.If you want to do some data minding, it is better to do it in local apps because of the io. It's cool to do it on the brower,but there must be some reasons why the browser deveplpers aren't interested in webcl.Camparing to develop on browser, I think you can do it better to make a gpu computing service, make a server runing cuda to support what you want to do.
